#!/usr/bin/perl

use POSIX;
use XML::Parser;

# http://b.tiles.mapbox.com/v3/brunosan.Mamou/11/955/964.png
#http://www.overpass-api.de/api/xapi?map?bbox=-122.51781,37.716045,-122.34924,37.817006

$minlat = 37.716045;
$minlon = -122.51781;
$maxlat = 37.817006;
$maxlon = -122.34924;

$head = "{\"type\": \"FeatureCollection\", \"features\": [ ";
$body = "";
$foot = "]}";
sub handle_start {

	my ($expat, $element, @tags) = @_;
	my %tags = @tags;

	if ($element eq "node") {
		$lat = $tags{'lat'};
		$lon = $tags{'lon'};

		if ($lat >= $minlat && $lat <= $maxlat && $lon >= $minlon && $lon <= $maxlon) {
			$lat{$tags{'id'}} = $lat;
			$lon{$tags{'id'}} = $lon;
		}
	}

	if ($element eq "way") {
		$timestamp = $tags{'timestamp'};
		$user = $tags{'user'};
		@nd = ();
	}

	if ($element eq "nd") {
		push @nd, $tags{'ref'};
	}
}

sub handle_end {
	my ($expat, $element,) = @_;

	if ($element eq "way") {
		@lat = ();
		@lon = ();

		for $n (@nd) {
			if (defined($lat{$n})) {
				push @lat, $lat{$n};
				push @lon, $lon{$n};
			} else {
				push @lat, 0;
				push @lon, 0;
			}
		}
		

		for ($i = 0; $i < $#lat; $i++) {


			if ($lat[$i] != 0 && $lat[$i + 1] != 0) {
				#print "$lat[$i],$lon[$i] $lat[$i + 1],$lon[$i + 1] // $file $timestamp\n";
				print STDERR $user;
				if($user eq "dbaron"){
					print "   {
			      \"type\": \"Feature\",
			      \"properties\": {\"user\":\"$user\"},
			      \"geometry\": {
			        \"type\": \"LineString\",
			        \"coordinates\": [
			          [$lon[$i] , $lat[$i] ],
			          [$lon[$i + 1], $lat[$i + 1]]
			        ]
			      }
			    },";
				}
				
			}
		}
		
	}
}



#for $file (<*.osc.gz>) {

	$n1=$ARGV[0];
	#print STDERR $ARGV[0];
	$parser = new XML::Parser(Handlers => { Start => \&handle_start, End => \&handle_end, });
	print $head;
	open(IN, "zcat $n1 |");
	$parser->parse(*IN);
	print "{
			    \"type\": \"Feature\",
			    \"properties\": {},
			    \"geometry\": {
			    \"type\": \"LineString\",
			      \"coordinates\": []			       
			    }
			}";
	print $foot;
	close(IN);
#}
